language: emacs-lisp
before_install:
  - sudo mkdir /usr/local/evm
  - sudo chown travis:travis /usr/local/evm
  - curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash
  - export PATH="/home/travis/.evm/bin:$PATH"
  - evm install $EVM_EMACS
  - evm use $EVM_EMACS
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH="/home/travis/.cask/bin:$PATH"
  - cask
env:
  - EVM_EMACS=emacs-24.3-bin
script:
  - emacs --version
  - make test

